In [1]:
import matplotlib
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
import sklearn
import os
%matplotlib inline # wyłącznie w notatniku Jupyter 

In [2]:
HOUSING_PATH = os.path.join("zestaw danych","mieszkania")
def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, 'housing.csv')
    return pd.read_csv(csv_path)

In [3]:
df = load_housing_data()

In [4]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.3, random_state = 42)

In [7]:
test_set.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20046    -119.01     36.06                25.0       1505.0             NaN   
3024     -119.46     35.14                30.0       2943.0             NaN   
15663    -122.44     37.80                52.0       3830.0             NaN   
20484    -118.72     34.28                17.0       3051.0             NaN   
9814     -121.93     36.62                34.0       2351.0             NaN   

       population  households  median_income  median_house_value  \
20046      1392.0       359.0         1.6812             47700.0   
3024       1565.0       584.0         2.5313             45800.0   
15663      1310.0       963.0         3.4801            500001.0   
20484      1705.0       495.0         5.7376            218600.0   
9814       1063.0       428.0         3.7250            278000.0   

      ocean_proximity  
20046          INLAND  
3024           INLAND  
15663        NEAR BAY  
20484       <1H OCEAN  
9814       NEAR OCEAN

In [12]:
# podział
housing  = train_set.drop("median_house_value", axis=1 )
housing_labels = train_set['median_house_value'].copy()

In [15]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7061     -118.02     33.93                35.0       2400.0           398.0   
14689    -117.09     32.79                20.0       2183.0           534.0   
17323    -120.14     34.59                24.0       1601.0           282.0   
10056    -121.00     39.26                14.0        810.0           151.0   
15750    -122.45     37.77                52.0       3188.0           708.0   

       population  households  median_income ocean_proximity  
7061       1218.0       408.0         4.1312       <1H OCEAN  
14689       999.0       496.0         2.8631      NEAR OCEAN  
17323       731.0       285.0         4.2026      NEAR OCEAN  
10056       302.0       138.0         3.1094          INLAND  
15750      1526.0       664.0         3.3068        NEAR BAY

## Oczyszczanie danych

### Braki danych

#### usunięcie braków danych


In [41]:
housing.dropna(subset=['total_bedrooms']).head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7061     -118.02     33.93                35.0       2400.0           398.0   
14689    -117.09     32.79                20.0       2183.0           534.0   
17323    -120.14     34.59                24.0       1601.0           282.0   
10056    -121.00     39.26                14.0        810.0           151.0   
15750    -122.45     37.77                52.0       3188.0           708.0   

       population  households  median_income ocean_proximity  
7061       1218.0       408.0         4.1312       <1H OCEAN  
14689       999.0       496.0         2.8631      NEAR OCEAN  
17323       731.0       285.0         4.2026      NEAR OCEAN  
10056       302.0       138.0         3.1094          INLAND  
15750      1526.0       664.0         3.3068        NEAR BAY

#### usunięcie całej kolumnny

In [42]:
housing.drop("total_bedrooms", axis= 1).head()

longitude  latitude  housing_median_age  total_rooms  population  \
7061     -118.02     33.93                35.0       2400.0      1218.0   
14689    -117.09     32.79                20.0       2183.0       999.0   
17323    -120.14     34.59                24.0       1601.0       731.0   
10056    -121.00     39.26                14.0        810.0       302.0   
15750    -122.45     37.77                52.0       3188.0      1526.0   

       households  median_income ocean_proximity  
7061        408.0         4.1312       <1H OCEAN  
14689       496.0         2.8631      NEAR OCEAN  
17323       285.0         4.2026      NEAR OCEAN  
10056       138.0         3.1094          INLAND  
15750       664.0         3.3068        NEAR BAY

#### Imputacja poprzez medianę

In [43]:
median = housing["total_bedrooms"].median()
housing['total_bedrooms'].fillna(median)
# housing['total_bedrooms'].fillna(median, inplace=True)

7061      398.0
14689     534.0
17323     282.0
10056     151.0
15750     708.0
15283    2041.0
18551     421.0
7555      225.0
15700     535.0
12364     920.0
7552      299.0
2478      356.0
1197      154.0
18932     255.0
18438     624.0
19570     354.0
13563     343.0
8442      388.0
1808       75.0
18172     437.0
15258     493.0
7085      233.0
17385    1115.0
263       502.0
9675      697.0
19887     323.0
19046     135.0
12308     145.0
18906     671.0
19500     459.0
          ...  
1267      225.0
1899      422.0
3005      635.0
19118     393.0
189       395.0
2747      235.0
18431     280.0
18942     858.0
8666     1611.0
6396      250.0
19769     214.0
17568     492.0
6420     1289.0
5051      359.0
5311      267.0
2433      294.0
769       200.0
1685      622.0
8322      550.0
16023     438.0
11363     840.0
14423     263.0
4426     1420.0
16850     264.0
6265      324.0
11284     201.0
11964     570.0
5390      569.0
860       597.0
15795    1315.0
Name: total_bedrooms, Le

### Pakiet sklearn

In [25]:
from sklearn.preprocessing import Imputer
# from sklearn.impute import SimpleImputer # nowa wersja

In [31]:
imputer = Imputer(strategy="median")

/Users/air/Desktop/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [36]:
housing_num = housing.drop("ocean_proximity", axis=1)

In [37]:
housing_num.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7061     -118.02     33.93                35.0       2400.0           398.0   
14689    -117.09     32.79                20.0       2183.0           534.0   
17323    -120.14     34.59                24.0       1601.0           282.0   
10056    -121.00     39.26                14.0        810.0           151.0   
15750    -122.45     37.77                52.0       3188.0           708.0   
15283    -117.33     33.17                11.0      10923.0          2041.0   
18551    -122.03     36.96                28.0       1607.0           421.0   
7555     -118.19     33.91                33.0        915.0           225.0   
15700    -122.44     37.79                52.0       1817.0           535.0   
12364    -116.46     33.82                 6.0       4863.0           920.0   

       population  households  median_income  
7061       1218.0       408.0         4.1312  
14689       999.0       496.0         2.8631  
17323       731.0       285.0         4.2026  
10056       302.0       138.0         3.1094  
15750      1526.0       664.0         3.3068  
15283      4773.0      1858.0         4.0791  
18551       926.0       385.0         2.4250  
7555        826.0       212.0         2.7708  
15700       800.0       487.0         3.9750  
12364      3010.0       828.0         3.9508

In [44]:
imputer.fit(housing_num) # statystyka
X = imputer.transform(housing_num) 
housing_tr = pd.DataFrame(X, columns=housing_num.columns)

### zmienne kategoryjne 

In [46]:
housing_cat = housing['ocean_proximity']
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
housing_cat_encoded = encoder.fit_transform(housing_cat)
housing_cat_encoded
print(encoder.classes_)

['<1H OCEAN' 'INLAND' 'ISLAND' 'NEAR BAY' 'NEAR OCEAN']


## Kodowanie one-hot encoding

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [50]:
encoder = OneHotEncoder()
housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1))

/Users/air/Desktop/venv/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [51]:
housing_cat_1hot.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

### przy uzyciu jednej funkcji


In [53]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
housing_cat_1hot = encoder.fit_transform(housing_cat)
housing_cat_1hot

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       ...,
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0]])

### Niestandardowe transformacje 

np. czyszczenie danych lub łączenie atrybutów

Transformacje możesz wykonywać bezpośrednio na danych ale ... 

Możesz też napisać je zgodnie z sklearn. Aby to uczynić stwórz klasę z trzema metodami: 

`fit()` zwracająca `self`

`transform()` 

`fit_transform()`




In [66]:
from sklearn.base import BaseEstimator, TransformerMixin

rooms_ix, bedrooms_ix, population_ix, household_ix = 3,4,5,6 

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        Pokoje_na_rodzine = X[:, rooms_ix]/X[:, household_ix]
        Populacja_na_rodzine = X[:, population_ix] / X[:, household_ix] 
        if self.add_bedrooms_per_room:
            Sypialnie_na_pokoje = X[:, bedrooms_ix] / X[:, rooms_ix] 
            return np.c_[X, Pokoje_na_rodzine, Populacja_na_rodzine, Sypialnie_na_pokoje]
        else:
            return np.c_[X, Pokoje_na_rodzine, Populacja_na_rodzine]

In [67]:
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [68]:
housing_extra_attribs

array([[-118.02, 33.93, 35.0, ..., '<1H OCEAN', 5.882352941176471,
        2.985294117647059],
       [-117.09, 32.79, 20.0, ..., 'NEAR OCEAN', 4.401209677419355,
        2.0141129032258065],
       [-120.14, 34.59, 24.0, ..., 'NEAR OCEAN', 5.617543859649123,
        2.5649122807017544],
       ...,
       [-118.38, 34.03, 36.0, ..., '<1H OCEAN', 3.9867172675521823,
        3.332068311195446],
       [-121.96, 37.58, 15.0, ..., '<1H OCEAN', 6.395348837209302,
        3.178890876565295],
       [-122.42, 37.77, 52.0, ..., 'NEAR BAY', 3.4025764895330113,
        2.108695652173913]], dtype=object)

### W jaki sposób skalują dane numeryczne metody MinMaxScaler oraz StandardScaler 

### Potoki transformacji

In [69]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
('imputer', Imputer(strategy="median")),
('attribs_adder', CombinedAttributesAdder()),
('std_scaler', StandardScaler()),
])

housing_num_tr_pip = num_pipeline.fit_transform(housing_num)

housing_num_tr_pip

/Users/air/Desktop/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 0.78093406, -0.80568191,  0.50935748, ...,  0.18106017,
        -0.01082519, -0.80919934],
       [ 1.24526986, -1.33947268, -0.67987313, ..., -0.42262953,
        -0.08931585,  0.5409245 ],
       [-0.27755183, -0.49664515, -0.36274497, ...,  0.07312833,
        -0.04480037, -0.63257554],
       ...,
       [ 0.60119118, -0.75885816,  0.58863952, ..., -0.59156984,
         0.01720102,  0.99001519],
       [-1.18625198,  0.90338501, -1.07628333, ...,  0.39014889,
         0.00482125, -0.78932602],
       [-1.41592345,  0.99235014,  1.85715216, ..., -0.82965604,
        -0.0816717 ,  1.68141644]])

In [71]:
from sklearn.base import BaseEstimator, TransformerMixin
class DataFrameSelector(BaseEstimator, TransformerMixin): 
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names 
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

num_attribs = list(housing_num) 
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
('selector', DataFrameSelector(num_attribs)), 
('imputer', Imputer(strategy="median")),
('attribs_adder', CombinedAttributesAdder()),
('std_scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
('selector', DataFrameSelector(cat_attribs)),
('cat_encoder', LabelBinarizer()),
])

/Users/air/Desktop/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [73]:
num_pipeline

Pipeline(memory=None,
     steps=[('selector', DataFrameSelector(attribute_names=['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income'])), ('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)), ('attribs_adder', CombinedAttributesAdder(add_bedrooms_per_room=True)), ('std_scaler', StandardScaler(copy=True, with_mean=True, with_std=True))])

In [74]:
cat_pipeline

Pipeline(memory=None,
     steps=[('selector', DataFrameSelector(attribute_names=['ocean_proximity'])), ('cat_encoder', LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False))])

In [77]:
from sklearn.pipeline import FeatureUnion

full_pipeline = FeatureUnion(transformer_list=[ 
    ("num_pipeline", num_pipeline),
    ("cat_pipeline", cat_pipeline),
])

In [80]:
housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared.shape

TypeError: fit_transform() takes 2 positional arguments but 3 were given

In [81]:
class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, sparse_output=False):
        self.sparse_output = sparse_output
    def fit(self, X, y=None):
        self.enc = LabelBinarizer(sparse_output=self.sparse_output)
        self.enc.fit(X)
        return self
    def transform(self, X, y=None):
        return self.enc.transform(X)

In [82]:
num_pipeline = Pipeline([
('selector', DataFrameSelector(num_attribs)), 
('imputer', Imputer(strategy="median")),
('attribs_adder', CombinedAttributesAdder()),
('std_scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
('selector', DataFrameSelector(cat_attribs)),
('cat_encoder', CustomLabelBinarizer()),
])

/Users/air/Desktop/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [83]:
full_pipeline = FeatureUnion(transformer_list=[ 
    ("num_pipeline", num_pipeline),
    ("cat_pipeline", cat_pipeline),
])

In [84]:
housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared.shape

(14448, 16)

## MODEL

In [85]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [87]:
some_data = housing.iloc[:5]
some_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7061     -118.02     33.93                35.0       2400.0           398.0   
14689    -117.09     32.79                20.0       2183.0           534.0   
17323    -120.14     34.59                24.0       1601.0           282.0   
10056    -121.00     39.26                14.0        810.0           151.0   
15750    -122.45     37.77                52.0       3188.0           708.0   

       population  households  median_income ocean_proximity  
7061       1218.0       408.0         4.1312       <1H OCEAN  
14689       999.0       496.0         2.8631      NEAR OCEAN  
17323       731.0       285.0         4.2026      NEAR OCEAN  
10056       302.0       138.0         3.1094          INLAND  
15750      1526.0       664.0         3.3068        NEAR BAY

In [88]:
some_labels = housing_labels.iloc[:5]
some_labels

7061     193800.0
14689    169700.0
17323    259800.0
10056    136100.0
15750    500001.0
Name: median_house_value, dtype: float64

In [89]:
some_data_prepared = full_pipeline.transform(some_data)

In [90]:
print("Prognozy:", lin_reg.predict(some_data_prepared))

Prognozy: [221608.71694073 196160.20621852 261964.70699839  70926.09270578
 256891.00870896]


In [91]:
print("Rzeczywistość:", list(some_labels))

Rzeczywistość: [193800.0, 169700.0, 259800.0, 136100.0, 500001.0]


In [92]:
from sklearn.metrics import mean_squared_error

In [93]:
housing_predictions = lin_reg.predict(housing_prepared)

In [94]:
lin_mse = mean_squared_error(housing_labels, housing_predictions)

In [95]:
lin_rmse = np.sqrt(lin_mse)

In [96]:
lin_rmse

67881.61208813675

## A inny model ? 

In [97]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(housing_prepared, housing_labels)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [98]:
housing_predictions = tree_reg.predict(housing_prepared)

In [99]:
tree_mse = mean_squared_error(housing_labels, housing_predictions)

In [100]:
tree_rmse = np.sqrt(tree_mse)

In [101]:
tree_rmse

0.0

In [102]:
from sklearn.model_selection import cross_val_score

In [103]:
scores = cross_val_score(tree_reg, housing_prepared, housing_labels,
scoring="neg_mean_squared_error", cv=10)

In [105]:
tree_rmse_scores = np.sqrt(-scores)
tree_rmse_scores

array([74469.59251107, 73004.37717205, 73197.16054895, 73805.19716912,
       69262.1245512 , 71676.34793716, 68717.57879615, 68493.24846002,
       67138.59727521, 67720.56833123])

In [106]:
def wyniki(scores):
    print("Wyniki", scores)
    print("Średnio", scores.mean())
    print("Odchylenie std", scores.std())
    

In [108]:
wyniki(tree_rmse_scores)

Wyniki [74469.59251107 73004.37717205 73197.16054895 73805.19716912
 69262.1245512  71676.34793716 68717.57879615 68493.24846002
 67138.59727521 67720.56833123]
Średnio 70748.47927521501
Odchylenie std 2622.1294674762744


In [109]:
lin_scores = cross_val_score(lin_reg, housing_prepared, housing_labels, scoring="neg_mean_squared_error", cv=10)

In [110]:
lin_rmse_scores = np.sqrt(-lin_scores)

In [112]:
wyniki(lin_rmse_scores)

Wyniki [70880.18689495 67409.11219521 66718.50669456 66644.24144927
 67870.5024128  65300.94909237 65376.95506465 68531.90978125
 74995.3725312  68145.24576002]
Średnio 68187.29818762788
Odchylenie std 2742.1779032896425


## Sprawdz model lasów losowych

## Zapisz model 

In [ ]:
from sklearn.externals import joblib
# zapisz
joblib.dump(my_model, "mój_model.pkl")
# zaladuj
my_model_loaded = joblib.load("mój_model.pkl")
